variables:
  CONTAINER_IMAGE: registry.courierZ.com/$CI_PROJECT_PATH
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

stages:
  - stage

services:
  - docker:dind

stage:
  stage: stage
  image: docker:stable
  tags:
    - dnd
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.courierZ.com
    - docker build  -f Dockerfile -t $CONTAINER_IMAGE:test .
    - docker push $CONTAINER_IMAGE:test
